version: "3"
services:
  mymongodb:
    image: mongo:latest
    container_name: "mymongodb"
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_INITDB_DATABASE: product-db
    ports:
      - 27017:27017
    volumes:
    - './data:/data/db'

  springboot-mongodb:
    build:
      context: .
      dockerfile: Dockerfile
    image: spring-mongodb:1.0
    container_name: spring-mongodb
    ports:
      - 8080:8080
    links:
      - mymongodb